# permissions for end users to edit sharedmemories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharedmemory-editor-role
rules:
- apiGroups:
  - is.github.com
  resources:
  - sharedmemories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - is.github.com
  resources:
  - sharedmemories/status
  verbs:
  - get
