# permissions for end users to view sharedmemories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharedmemory-viewer-role
rules:
- apiGroups:
  - is.github.com
  resources:
  - sharedmemories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - is.github.com
  resources:
  - sharedmemories/status
  verbs:
  - get
